config/routes.rb
Rails.application.routes.draw do

  resources :cities

  resources :stocks

  resources :ventaprods

  resources :rendicionprods

  resources :entregaprods

  resources :rehabs, :except => [ :index]

  resources :egreso_internos

  resources :court_orders, :except => [ :index]

  resources :contacts, :except => [ :index]

  resources :ingresos

  resources :venta

  resources :entrega_productos

  resources :rendicion_productos

  resources :conducta

  resources :hijos, :except => [ :index]

  resources :voluntarios

  resources :conyugues, :except => [ :index]

  resources :internos

  resources :produccions

  resources :historia_clinicas

  resources :egresos

  resources :avaluo_donativos

  resources :recepcion_donativos

  resources :cita

  resources :products

  get '/egresos/buscar_reporte' => 'egresos#buscar_reporte', :as => 'buscar_reporte'
  get '/egresos/buscar_entre_fechas' => 'egresos#buscar_entre_fechas', :as => 'buscar_entre_fechas'

  get '/historia_clinicas/new/:id' => 'historia_clinicas#new', :as => 'historia'
  get '/egreso_internos/new/:id' => 'egreso_internos#new', :as => 'egreso_inter'

  get '/conyugues/new/:id' => 'conyugues#new', :as => 'pareja'

   get '/contacts/new/:id' => 'contacts#new', :as => 'contacto'

  get '/hijos/new/:id' => 'hijos#new', :as => 'fis'

  get '/conductas/new/:id' => 'conducta#new', :as => 'memo'

  get '/court_orders/new/:id' => 'court_orders#new', :as => 'orden'

  get '/referencias/new/:id' => 'referencias#new', :as => 'respalda'

  get '/rehabs/new/:id' => 'rehabs#new', :as => 'rehaba'

  get '/entrega_productos/new/:id' => 'entrega_productos#new', :as => 'entrega'
  get '/products/search' => 'products#search'

  get '/rendicion_productos/new/:id' => 'rendicion_productos#new', :as => 'rendicion'

  get '/rendicionprods/new/:id' => 'rendicionprods#new', :as => 'rend'

  get '/ventaprods/new/:id/:rendicion_id' => 'ventaprods#new', :as => 'vent'

  get '/ingresos/new/:id/:donaid' => 'ingresos#new', :as => 'ingre'  

  

   root 'welcome#index'
    get 'welcome/index'

end

app/models/entrega_producto.rb
class EntregaProducto < ActiveRecord::Base
  belongs_to :product
  belongs_to :voluntario
  has_many :rendicionProductos

  validates :cantidad, presence: {:message => "- La cantidad es un campo obligatorio"}
  validates :cantidad, :numericality => {:greater_than => 0, :message => "- La cantidad debe ser mayor a 0"}

  before_save :default_values

  def default_values
    self.estado ||= 'true'
  end

  validate :date_cannot_be_in_the_future

  def date_cannot_be_in_the_future
    errors.add(:fecha, "No se registran entregas a futuro") if
      !self.fecha.blank? and self.fecha > Date.today
    end
end

app/controllers/entrega_productos_controller.rb
class EntregaProductosController < ApplicationController
  before_action :set_entrega_producto, only: [:show, :edit, :update, :destroy]

  # GET /entrega_productos
  # GET /entrega_productos.json
  def index
    @entrega_productos = EntregaProducto.all
  end

  # GET /entrega_productos/1
  # GET /entrega_productos/1.json
  def show
    @entrega_producto=EntregaProducto.find(params[:id])
    @rendicion_producto=@entrega_producto.rendicion_producto
  end

  # GET /entrega_productos/new
  def new
    @entrega_producto = EntregaProducto.new
    @id=(params[:id])
    @voluntarios = Voluntario.all
    @productos = Producto.all
    if @voluntarios == nil
        flash[:success] =  'Por favor Registre al menos un Voluntario' 
        redirect_to '/voluntarios'
      else
        render action: "new"
      end
  end

  # GET /entrega_productos/1/edit
  def edit
  end

  # POST /entrega_productos
  # POST /entrega_productos.json
  def create
    @entrega_producto = EntregaProducto.new(entrega_producto_params)
    @entrega_producto.voluntario_id=params[:voluntario_id]

      if @entrega_producto.save
        flash[:success] =  'Entrega producto creado exitosamente' 
        redirect_to '/entrega_productos'
      else
        render action: "new"
      end
  end

  # PATCH/PUT /entrega_productos/1
  # PATCH/PUT /entrega_productos/1.json
  def update
      if @entrega_producto.update(entrega_producto_params)
        flash[:success] =  'Entrega producto actualizado exitosamente' 
        redirect_to '/entrega_productos'
      else
        render action: "new"
      end
  end

  # DELETE /entrega_productos/1
  # DELETE /entrega_productos/1.json
  def destroy
    @entrega_producto.destroy
    respond_to do |format|
      format.html { redirect_to entrega_productos_url, notice: 'Entrega producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entrega_producto
      @entrega_producto = EntregaProducto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entrega_producto_params
      params.require(:entrega_producto).permit(:fecha, :hora, :cantidad, :estado, :product_id, :voluntario_id)
    end
end

app/helpers/entrega_productos_helper.rb
module EntregaProductosHelper
end

app/views/entrega_productos/_form.html.erb
<%= form_for(@entrega_producto) do |f| %>
  <% if @entrega_producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entrega_producto.errors.count, "error") %>, corrija los siguientes errores:</h2>

      <ul>
      <% @entrega_producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<input type="hidden" name="voluntario_id" value="<%= @id %>" >
  <div class="field">
    <%= f.label :fecha, 'Fecha (*)'%><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :hora %><br>
    <%= f.time_select :hora %>
  </div>
  <div class="field">
    <%= f.label :cantidad, 'Cantidad (*)' %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <% f.collection_select(:product_id, Product.all, :id, :code) %>
    <%= :voluntario_id %>
  </div>
  <div class="field">
    <% f.label :voluntario %><br>
    <% f.collection_select(:voluntario_id, Voluntario.all, :id, :full_name) %>
  </div>
  <div class="actions">
    <%= f.submit (@entrega_producto.new_record? ? 'Registrar Entrega' : 'Editar Entrega'),:class => 'btn btn-mini btn-success active'%>
  </div>
<% end %>

app/views/entrega_productos/edit.html.erb
<h1>Editar entrega de productos</h1>

<%= render 'form' %>

<%= link_to 'Atras', entrega_productos_path, :class => 'btn btn-mini btn-default'%>

app/views/entrega_productos/index.html.erb
<h1>Lista entrega de productos</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Fecha</th>
      <th>Cantidad</th>
      <th>Product</th>
      <th>Voluntario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entrega_productos.each do |entrega_producto| %>
      <tr>
        <td><%= entrega_producto.id %></td>D
        <td><%= entrega_producto.fecha %></td>
        <td><%= entrega_producto.cantidad %></td>

        <td><%= entrega_producto.product_id %></td>
        <td><%= entrega_producto.voluntario_id %></td>

        <td><%= link_to 'Mostrar', entrega_producto, :class => 'btn btn-mini btn-info active'%> <%= link_to 'Editar', edit_entrega_producto_path(entrega_producto), :class => 'btn btn-mini btn-warning active'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Crear Entrega producto', new_entrega_producto_path,:class => 'btn btn-mini btn-success active'%>

app/views/entrega_productos/new.html.erb
<style type="text/css">
#cuadro {	
	padding: 70px 0 0 0px;
	height: 100%;
}
#cuadro {
	width: 350px;
	margin:auto;
	position: relative;
}
</style>
<div class="cuadro">
<h1>Crear entrega producto</h1>

<%= render 'form' %>

<%= link_to 'Atras', entrega_productos_path, :class => 'btn btn-mini btn-default'%>
</div>

app/views/entrega_productos/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-striped">
  <thead>
    <tr>
      <div><strong>Voluntario: </strong> <%= @entrega_producto.voluntario.full_name %><br>
        <strong>Producto: </strong> <%= @entrega_producto.product.code %>
      </div>
    </tr>
    <tr>
      <th>
      </th>
      <th>
        Productos Entregados
      </th>
      <th>
        <% if @rendicion_producto== nil %>
          <%= link_to 'Registrar Rendicion', rendicion_path(@entrega_producto.id),:class => 'btn btn-mini btn-success active' %>
        <% end %>
        <% if @rendicion_producto != nil %>           
          Productos Devueltos
        <% end %>         
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <strong>Id:</strong>
      </td>
      <td>
        <%= @entrega_producto.id %>
      </td>
      <td>
        <% if @rendicion_producto != nil %> 
          <%= @rendicion_producto.id %>               
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>Cantidad:</strong>
      </td>
      <td>
        <%= @entrega_producto.cantidad %>
      </td>
      <td>
        <% if @rendicion_producto != nil %> 
          <%= @rendicion_producto.cantidad %>                
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>Fecha:</strong>
      </td>
      <td>
        <%= @entrega_producto.fecha %>
      </td>
      <td>
        <% if @rendicion_producto != nil %> 
          <%= @rendicion_producto.fecha %>              
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>Hora:</strong>
      </td>
      <td>
        <%= @entrega_producto.hora.strftime("%I:%M %p") %>
      </td>
      <td>
        <% if @rendicion_producto != nil %> 
          <%= @rendicion_producto.hora.strftime("%I:%M %p") %>             
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
      </td>
      <td></td>
      <td>
        <% if @rendicion_producto != nil %> 
          <strong>Observaciones:</strong>
          <%= @rendicion_producto.observaciones %>
        <% end %>
      </td>
    </tr>    
    <tr>
      <td>
      </td>
      <td></td>
      <td>
        <% if @rendicion_producto != nil %> 
          <%= link_to 'Editar Rendicon', edit_rendicion_producto_path(@rendicion_producto.id), :class => 'btn btn-mini btn-warning active'%>
        <% end %>
      </td>
    </tr>   
  </tbody>
</table>


<%= link_to 'Atras', entrega_productos_path,:class => 'btn btn-mini btn-default'%>