config/routes.rb
Rails.application.routes.draw do

  resources :cities

  resources :stocks

  resources :ventaprods

  resources :rendicionprods

  resources :entregaprods

  resources :rehabs, :except => [ :index]

  resources :egreso_internos

  resources :court_orders, :except => [ :index]

  resources :contacts, :except => [ :index]

  resources :ingresos

  resources :venta

  resources :entrega_productos

  resources :rendicion_productos

  resources :conducta

  resources :hijos, :except => [ :index]

  resources :voluntarios

  resources :conyugues, :except => [ :index]

  resources :internos

  resources :produccions

  resources :historia_clinicas

  resources :egresos

  resources :avaluo_donativos

  resources :recepcion_donativos

  resources :cita

  resources :products

  get '/egresos/buscar_reporte' => 'egresos#buscar_reporte', :as => 'buscar_reporte'
  get '/egresos/buscar_entre_fechas' => 'egresos#buscar_entre_fechas', :as => 'buscar_entre_fechas'

  get '/historia_clinicas/new/:id' => 'historia_clinicas#new', :as => 'historia'
  get '/egreso_internos/new/:id' => 'egreso_internos#new', :as => 'egreso_inter'

  get '/conyugues/new/:id' => 'conyugues#new', :as => 'pareja'

   get '/contacts/new/:id' => 'contacts#new', :as => 'contacto'

  get '/hijos/new/:id' => 'hijos#new', :as => 'fis'

  get '/conductas/new/:id' => 'conducta#new', :as => 'memo'

  get '/court_orders/new/:id' => 'court_orders#new', :as => 'orden'

  get '/referencias/new/:id' => 'referencias#new', :as => 'respalda'

  get '/rehabs/new/:id' => 'rehabs#new', :as => 'rehaba'

  get '/entrega_productos/new/:id' => 'entrega_productos#new', :as => 'entrega'
  get '/products/search' => 'products#search'

  get '/rendicion_productos/new/:id' => 'rendicion_productos#new', :as => 'rendicion'

  get '/rendicionprods/new/:id' => 'rendicionprods#new', :as => 'rend'

  get '/ventaprods/new/:id/:rendicion_id' => 'ventaprods#new', :as => 'vent'

  get '/ingresos/new/:id/:donaid' => 'ingresos#new', :as => 'ingre'  

  

   root 'welcome#index'
    get 'welcome/index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="container">
	 
	<div class="jumbotron">
		<img src="/images/remar.png" width="1020">
	</div>

	<div class="row menu">
		<div class="col-lg-6">
			<%= link_to 'Internos', internos_path %>
		</div>
		<div class="col-lg-6">
			<%= link_to 'Cita', cita_path %>
		</div>
		<div class="col-lg-6">
			<%= link_to 'Egreso', egresos_path %>
		</div>
		<div class="col-lg-6">
			<%= link_to 'Recepcion de Donativos', recepcion_donativos_path %>
		</div>
		<div class="col-lg-6">
			<%= link_to 'Producto', products_path %>
		</div>
		<div class="col-lg-6">
			<%= link_to 'Ingresos', ingresos_path %>
		</div>
		<div class="col-lg-6">
			<%= link_to 'Produccion', produccions_path %>
		</div>
		<div class="col-lg-6">
			<%= link_to 'Voluntarios', voluntarios_path %>
		</div>
		<div class="col-lg-6"></div>
		<div class="col-lg-6">
			<%= link_to 'Ventas','/entregaprods?&page=1' %>
		</div>	
	</div>
</div>
<br><br><br><br><br><br>
<div class="navbar navbar-inverse" id="pie_pagina">
		<div class="row">
			<div class="col-md-4">
				<font color="white"><strong>Elaborador por:</strong></font>
			</div>
			<div class="col-md-4">
				<font color="white">
					<p>Howard Castillo Balboa</p>
					<p>Lesly Méndez Cruz</p>
					<p>Guido Vildozo Méndez</p>
				</font>
			</div>
			<div class="col-md-4">
				<img src="/images/logo_cato.png" alt="rss feed" width="70"/>
			</div>
		</div>
		<div align="right">
			<font color="white"><p>Taller de Sistemas de Información - Copyright © 2015</p></font>
		</div>
</div>