config/routes.rb
Rails.application.routes.draw do

  resources :cities

  resources :stocks

  resources :ventaprods

  resources :rendicionprods

  resources :entregaprods

  resources :rehabs, :except => [ :index]

  resources :egreso_internos

  resources :court_orders, :except => [ :index]

  resources :contacts, :except => [ :index]

  resources :ingresos

  resources :venta

  resources :entrega_productos

  resources :rendicion_productos

  resources :conducta

  resources :hijos, :except => [ :index]

  resources :voluntarios

  resources :conyugues, :except => [ :index]

  resources :internos

  resources :produccions

  resources :historia_clinicas

  resources :egresos

  resources :avaluo_donativos

  resources :recepcion_donativos

  resources :cita

  resources :products

  get '/egresos/buscar_reporte' => 'egresos#buscar_reporte', :as => 'buscar_reporte'
  get '/egresos/buscar_entre_fechas' => 'egresos#buscar_entre_fechas', :as => 'buscar_entre_fechas'

  get '/historia_clinicas/new/:id' => 'historia_clinicas#new', :as => 'historia'
  get '/egreso_internos/new/:id' => 'egreso_internos#new', :as => 'egreso_inter'

  get '/conyugues/new/:id' => 'conyugues#new', :as => 'pareja'

   get '/contacts/new/:id' => 'contacts#new', :as => 'contacto'

  get '/hijos/new/:id' => 'hijos#new', :as => 'fis'

  get '/conductas/new/:id' => 'conducta#new', :as => 'memo'

  get '/court_orders/new/:id' => 'court_orders#new', :as => 'orden'

  get '/referencias/new/:id' => 'referencias#new', :as => 'respalda'

  get '/rehabs/new/:id' => 'rehabs#new', :as => 'rehaba'

  get '/entrega_productos/new/:id' => 'entrega_productos#new', :as => 'entrega'
  get '/products/search' => 'products#search'

  get '/rendicion_productos/new/:id' => 'rendicion_productos#new', :as => 'rendicion'

  get '/rendicionprods/new/:id' => 'rendicionprods#new', :as => 'rend'

  get '/ventaprods/new/:id/:rendicion_id' => 'ventaprods#new', :as => 'vent'

  get '/ingresos/new/:id/:donaid' => 'ingresos#new', :as => 'ingre'  

  

   root 'welcome#index'
    get 'welcome/index'

end

app/models/conyugue.rb
class Conyugue < ActiveRecord::Base
	belongs_to :interno
	before_save :default_values

  def default_values
    self.estado ||= 'true'
  end


def full_name
  "#{self.nombre} #{self.apellido1} #{self.apellido2}"
end

  	validates :ci, presence: {:message => "- El carnet es un campo obligatorio"}
	validates :ci, uniqueness: { :message => "- El carnet ya existe"}
	validates :ci, format: { allow_blank: true,with: /\A[+-]?\d+\Z/, message: " Solo se aceptan numeros"}
	validates :ci, length: { maximum: 7, too_long: "- %{count} caracteres es la longitud maxima permitida" }
	validates :ci, length: { allow_blank: true, minimum: 6, muy_corto: "- %{count} caracteres es la longitud minima permitida" }
	
	validates :apellido1, presence: {:message => "- El apellido Paterno es un campo obligatorio"}
	validates :apellido1, format: { with: /\A[a-zA-Z\W]+\z/, allow_blank: true, message: "- Solo se aceptan letras"}
	validates :apellido1, length: { maximum: 25, too_long: "- %{count} caracteres es la longitud maxima permitida para apellido Paterno" }

	validates :apellido2, format: { with: /\A[a-zA-Z\W ]+\z/, allow_blank: true, message: "- Solo se aceptan letras"}
	validates :apellido2, length: { maximum: 25, too_long: "- %{count} caracteres es la longitud maxima permitida para apellido Materno" }

	validates :nombre, presence: {:message => "- El nombre es un campo obligatorio"}
	validates :nombre, format: { with: /\A[a-zA-Z\W ]+\z/, allow_blank: true, message: "- Solo se aceptan letras"}
	validates :nombre, length: { maximum: 35, too_long: "- %{count} caracteres es la longitud maxima permitida para un nombre" }


	validates :direccion, presence: {:message => "- La Direccion es un campo obligatorio"}
	validates :direccion, length: { maximum: 35, too_long: "- %{count} caracteres es la longitud maxima permitida para un direccion" }
	validates :direccion, format: { with: /\A[a-zA-Z0-9 #\W]+\z/, allow_blank: true, message: "- Solo se aceptan letras"}



	validates :telefono, length: { maximum: 10, too_long: "- %{count} caracteres es la longitud maxima permitida" }
	validates :telefono, length: { minimum: 6, too_long: "- %{count} caracteres es la longitud minima permitida" }, :allow_blank => true
	validates :telefono,    :numericality => true, :allow_blank => true

	

	
	validates :lugarNacimiento, presence: {:message => "- Lugar de Nacimiento es un campo obligatorio"}
  
end

app/controllers/conyugues_controller.rb
class ConyuguesController < ApplicationController
  before_action :set_conyugue, only: [:show, :edit, :update, :destroy]

  # GET /conyugues
  # GET /conyugues.json
  def index
    @conyugues = Conyugue.all
    if(params["palabra"]!=nil)
        @conyugues=Conyugue.where("(nombre || ' ' || apellido1 || ' ' || apellido2) =?", params["palabra"])    
    end
    
  end

  # GET /conyugues/1
  # GET /conyugues/1.json
  def show
  end

  # GET /conyugues/new
  def new
    @conyugue = Conyugue.new
    @id=(params[:id])
    
    
  end

  # GET /conyugues/1/edit
  def edit
    
  end

  # POST /conyugues
  # POST /conyugues.json
  def create
    @conyugue = Conyugue.new(conyugue_params)
    @conyugue.interno_id=params[:interno_id]
    @interno=Interno.find(params[:interno_id])
    @id=@conyugue.interno_id
  
    

      if @conyugue.save
         flash[:success] = 'Conyugue fue creado exitosamente'
          redirect_to @interno 
      else
        render "new", :id => @conyugue.interno_id
        
      end
  
  end

  # PATCH/PUT /conyugues/1
  # PATCH/PUT /conyugues/1.json
  def update
    @conyugue.lugarNacimiento=(params[:palabra])
      if @conyugue.update(conyugue_params)
         flash[:success] = 'Conyugue fue creado exitosamente'
         redirect_to @conyugue 
      else
        render action: "edit"
      end
   
  end

  # DELETE /conyugues/1
  # DELETE /conyugues/1.json
  def destroy
    @conyugue.destroy
    respond_to do |format|
      format.html { redirect_to internos_path, notice: 'Conyugue fue borrado satisfactoriamente.' }
      format.json { head :no_content }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conyugue
      @conyugue = Conyugue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conyugue_params
      params.require(:conyugue).permit(:estado, :nombre, :apellido1, :apellido2, :ci, :lugarNacimiento, :fechaNacimiento, :telefono, :direccion)
    end
end

app/helpers/conyugues_helper.rb
module ConyuguesHelper
end

app/views/conyugues/_form.html.erb
<%= form_for(@conyugue) do |f| %>
  <% if @conyugue.errors.any? %>
    <div id="error_explanation">

      <h2><%= pluralize(@conyugue.errors.count, "error") %>, corrija los siguientes errores:</h2>


      <ul>
      <% @conyugue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <input type="hidden" name="interno_id" value="<%= @id %>" >
  


    
<table align="center" width="80%">
<tr>
  <td>
    <div class="field" align="center">
      <%= f.label :nombre, 'Nombre *' %><br>
      <%= f.text_field :nombre %>
    </div>
  </td>
  <td>
    <div class="field" align="center">
      <%= f.label :apellido1, 'Apellido Paterno *' %>   <br>
      <%= f.text_field :apellido1 %>
    </div>
  </td>
</tr>
<tr>
  <td>
    <div class="field" align="center">
       <%= f.label :apellido1, 'Apellido Materno' %><br>
      <%= f.text_field :apellido2 %>
    </div>
  </td>
  <td>
    <div class="field" align="center">
      <%= f.label :ci, 'CI *' %><br>
      <%= f.number_field :ci %>
    </div>
  </td>
</tr>
<tr>
  <td>
    <div class="field" align="center">
      <%= f.label :lugarNacimiento, 'Lugar de Nacimiento *' %><br>
      <%= f.select :lugarNacimiento, ['','
            DEPARTAMENTO DE COCHABAMBA','Arani','Arque','Cercado','Provincia Ayopaya','Bolívar','Capinota','Carrasco','Rodeado','Chapare','Esteban Arce','Germán Jordán','Provincia Mizque','Narciso Campero','Punata','Quillacollo','Tapacarí','Tiraque','','','
            
            DEPARTAMENTO DE SANTA CRUZ','ndrés Ibáñez','Provincia Ángel Sandoval','Chiquitos','Cordillera','Florida','Germán Busch','Guarayos','Ichilo','Ignacio Warnes','José Miguel de Velasco','Manuel María Caballero','Ñuflo de Chávez','Provincia obispo Santistevan','Sara Vallegrande','','',' 

            DEPARTAMENTO DE LA PAZ','Abel Iturralde','Aroma','Bautista Saavedra','Caranavi','Eliodoro Camacho','Franz Tamayo','Gualberto Villarroel','Provincia Ingavi','Provincia de Inquisivi','José Manuel Pando','José Ramón Loayza','Provincia de Larecaja','Los Andes','Provincia Manco Kapac','Provincia de muñecas','Nor Yungas','Provincia Omasuyos','Provincia Pacajes','Pedro Domingo Murillo','Sud Yungas','Lago Titicaca','','','

            DEPARTAMENTO DE BENI','Provincia de Cercado','Provincia Iténez','José Ballivián ','Mamoré','Provincia Marbán','Moxos','Vaca Díez','Yacuma','','','

            DEPARTAMENTO DE CHUQUISACA','Provincia de Belisario Boeto','Provincia de Hernando Siles','Provincia de Jaime Zudáñez','Provincia de Juana Azurduy de Padilla','Provincia de Luis Calvo','Provincia de Nor Cinti','Provincia de Oropeza','Provincia de Sud Cinti','Provincia de Tomina','Provincia de Yamparáez','','','
            
            DEPARTAMENTO DE ORURO','Atahuallpa','Provincia de Carangas','Rodeado','Eduardo Avaroa','Ladislao Cabrera','Costa','Nor Carangas','Pantaleón Dalence','Poopó','Puerto de Mejillones','Sajama','San Pedro de Totora','La provincia Saucarí','Provincia Sebastián Pagador','Provincia Sud Carangas','omas Barrón','','','
            
            DEPARTAMENTO DE PANDO','Provincia de Abuná','Federico Román','Madre de Dios','Provincia Manuripi','Nicolás Suárez','','','
            DEPARTAMENTO DE POTOSI','Alonso de Ibáñez','Antonio Quijarro','Bernardino Bilbao','Charcas','Provincia Chayanta','Cornelio Saavedra','Daniel Fields','Enrique Baldivieso','José María Linares','Modesto Omiste','Nor Chichas','Nor Lípez','Rafael Bustillo','Provincia de Sud Chichas','Sud Lípez','Tomás Frías','','','
                
            DEPARTAMENTO DE TARIJA','Aniceto Arce','Provincia de Burdet O’Connor','Provincia de Cercado','Eustaquio Méndez','Gran Chaco','José María Avilés'] %>
        </div>
      </td>
      <td>
          <div class="field" align="center">
            <%= f.label :fechaNacimiento, 'Fecha de Nacimiento' %><br>
            <%= f.date_select :fechaNacimiento, { order: [ :day, :month , :year], :start_year => Time.now.year-18, :end_year => Time.now.year-70} %>
           
          </div>
      </td>
  </tr>
<tr>
  <td>
    <div class="field" align="center">
      <%= f.label :telefono %><br>
      <%= f.number_field :telefono %>
    </div>
    </td>
    <td>
    <div class="field" align="center">
      <%= f.label :direccion, 'Direccion *' %><br>
      <%= f.text_area :direccion %>
    </div>
  </td>
</tr>
</table>

<br>
  <div align="center">
    <label>* Los campos con asterisco, son obligatorios. </label>
  </div><br><br>
<div>
  <div class="actions" align="center">
    <%= f.submit (@conyugue.new_record? ? 'Registrar Conyugue' : 'Guardar Conyugue') , :class => "btn btn-sm btn-success" %> |
    <% if @conyugue.interno_id==nil %>
        <%= link_to 'Retornar a interno',  :back, :class => 'btn btn-sm btn-default' %>
    <% else %>
        <a class='btn btn-sm btn-default' href=<%="/internos/"%>+<%=@conyugue.interno_id%> >Retornar a interno</a>
    <% end %>
  </div>

  


<% end %>

app/views/conyugues/edit.html.erb
<center>
	<div id="cuadro">
		<div id="titulo">Editar conyugue</div>
		<div id="linea"></div>
		<%= render 'form' %>
	</div>
</center>

app/views/conyugues/index.html.erb
<h1>Lista de Conyugues</h1>


<%= form_tag("/conyugues", method: "get") do %>
   

  <div id="the-basics" align="right"> 
    <input class="typeahead" type="text" name="palabra" placeholder="Inserte el dato a buscar"><br>
  </div>  

  <div align="right">
    <input type="submit" value="Buscar Conyugue">
  </div>

  <script type="text/javascript">
var substringMatcher = function(strs) {
  return function findMatches(q, cb) {
    var matches, substrRegex;

    // an array that will be populated with substring matches
    matches = [];

    // regex used to determine if a string contains the substring `q`
    substrRegex = new RegExp(q, 'i');

    // iterate through the pool of strings and for any string that
    // contains the substring `q`, add it to the `matches` array
    $.each(strs, function(i, str) {
      if (substrRegex.test(str)) {
        // the typeahead jQuery plugin expects suggestions to a
        // JavaScript object, refer to typeahead docs for more info
        matches.push({ value: str });
      }
    });

    cb(matches);
  };
};

<% @prueba=(@conyugues.map(&:full_name)).to_json.html_safe %>
var states = <%= @prueba %>;

$('#the-basics .typeahead').typeahead({
  hint: true,
  highlight: true,
  minLength: 1
},
{
  name: 'states',
  displayKey: 'value',
  source: substringMatcher(states)
});
</script>

<% end %>



 









<table class="table table-striped">
  <thead>
    <tr>
    
    
      <th>Nombre</th>
      <th>Apellido Paterno</th>
      <th>Apellido Materno</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conyugues.each do |conyugue| %>
      <tr>
        
       
        <td><%= conyugue.nombre %></td>
        <td><%= conyugue.apellido1 %></td>
        <td><%= conyugue.apellido2 %></td>
        <td><%= link_to 'Ver Conyugue', conyugue, :class => 'btn btn-mini btn-info active'  %></td>
        <td><%= link_to 'Editar Conyugue', edit_conyugue_path(conyugue),  :class => 'btn btn-mini btn-warning active'  %></td>
        <td><%= link_to 'Borrar Conyugue', conyugue, :class => 'btn btn-mini btn-success active', method: :delete, data: { confirm: 'Esta usted seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% link_to 'Registrar Conyugue', new_conyugue_path, :class => 'btn btn-mini btn-success active' %>

<h4><%= link_to 'Atras', :back, :class => 'btn btn-mini btn-default'  %></h4>

app/views/conyugues/new.html.erb
<center>
	<div id="cuadro">
		<div id="titulo">Nuevo Conyugue</div>
		<div id="linea"></div>
		<%= render 'form' %>
	</div>
</center>

app/views/conyugues/show.html.erb
<p id="notice"><%= notice %></p>

<br><br>
<div align="right">
   <a class='btn btn-mini btn-default' href=<%="/internos/"%>+<%=@conyugue.interno_id%> >Retornar a interno</a> 
</div>
<br>
<div class="jumbotron" align="center">
<p>
  <strong>Nombre:</strong>
  <%= @conyugue.nombre %>
</p>

<p>
  <strong>Apellido Paterno:</strong>
  <%= @conyugue.apellido1 %>
</p>

<p>
  <strong>Apellido Materno:</strong>
  <%= @conyugue.apellido2 %>
</p>

<p>
  <strong>CI:</strong>
  <%= @conyugue.ci %>
</p>

<p>
  <strong>Lugar de Nacimiento:</strong>
  <%= @conyugue.lugarNacimiento %>
</p>

<p>
  <strong>Fecha de Nacimiento:</strong>
  <%= @conyugue.fechaNacimiento.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @conyugue.telefono %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @conyugue.direccion %>
</p>
<br>
<div>

<% link_to 'Atras', conyugues_path, :class => 'btn btn-mini btn-default' %>