config/routes.rb
Rails.application.routes.draw do

  resources :cities

  resources :stocks

  resources :ventaprods

  resources :rendicionprods

  resources :entregaprods

  resources :rehabs, :except => [ :index]

  resources :egreso_internos

  resources :court_orders, :except => [ :index]

  resources :contacts, :except => [ :index]

  resources :ingresos

  resources :venta

  resources :entrega_productos

  resources :rendicion_productos

  resources :conducta

  resources :hijos, :except => [ :index]

  resources :voluntarios

  resources :conyugues, :except => [ :index]

  resources :internos

  resources :produccions

  resources :historia_clinicas

  resources :egresos

  resources :avaluo_donativos

  resources :recepcion_donativos

  resources :cita

  resources :products

  get '/egresos/buscar_reporte' => 'egresos#buscar_reporte', :as => 'buscar_reporte'
  get '/egresos/buscar_entre_fechas' => 'egresos#buscar_entre_fechas', :as => 'buscar_entre_fechas'

  get '/historia_clinicas/new/:id' => 'historia_clinicas#new', :as => 'historia'
  get '/egreso_internos/new/:id' => 'egreso_internos#new', :as => 'egreso_inter'

  get '/conyugues/new/:id' => 'conyugues#new', :as => 'pareja'

   get '/contacts/new/:id' => 'contacts#new', :as => 'contacto'

  get '/hijos/new/:id' => 'hijos#new', :as => 'fis'

  get '/conductas/new/:id' => 'conducta#new', :as => 'memo'

  get '/court_orders/new/:id' => 'court_orders#new', :as => 'orden'

  get '/referencias/new/:id' => 'referencias#new', :as => 'respalda'

  get '/rehabs/new/:id' => 'rehabs#new', :as => 'rehaba'

  get '/entrega_productos/new/:id' => 'entrega_productos#new', :as => 'entrega'
  get '/products/search' => 'products#search'

  get '/rendicion_productos/new/:id' => 'rendicion_productos#new', :as => 'rendicion'

  get '/rendicionprods/new/:id' => 'rendicionprods#new', :as => 'rend'

  get '/ventaprods/new/:id/:rendicion_id' => 'ventaprods#new', :as => 'vent'

  get '/ingresos/new/:id/:donaid' => 'ingresos#new', :as => 'ingre'  

  

   root 'welcome#index'
    get 'welcome/index'

end

app/models/egreso_interno.rb
class EgresoInterno < ActiveRecord::Base
  belongs_to :interno
  belongs_to :egreso

  validates :concepto, presence: {:message => "- Es un campo obligatorio"}
  validates :concepto, length: { maximum: 30, :message => "No debe tener mas de 50 caracteres"}

  validates :monto, presence: {:message => "- Es un campo obligatorio"}
  validates :monto, allow_blank: true, :numericality => {:greater_than => 0, :message => "- El monto debe ser mayor a 0"}
  validates :monto, length: {maximum: 10, too_long: "- %{count} caracteres es la longitud maxima permitida"}

  validates :fecha, presence: {:message => "- Es un campo obligatorio"}
  validates_date :fecha, :on => :create, :on_or_before => :today, :on_or_before_message => 'No se registran Egresos a futuro'

  def self.search(search)
  	if search
  		where('interno like ?', "%#{search}%")
  	else
  		scoped
  	end
  end

  def correspondeAinterno(interno)
    parametros = interno.split(' ')
    parametros.each do |parametro|
      if Interno.find(self.interno_id.to_i).nombre.downcase.include?(parametro.downcase)
        return true
      end
    end
    false
  end 
end

app/controllers/egreso_internos_controller.rb
class EgresoInternosController < ApplicationController
  before_action :set_egreso_interno, only: [:show, :edit, :update, :destroy]

  # GET /egreso_internos
  # GET /egreso_internos.json
  def index
    #@egreso_internos = EgresoInterno.all
    #@palabra = ''
    #@palabra = params[:palabra]
    #@egreso_internos = EgresoInterno.where("interno_id LIKE ?", "%#{@palabra}%")
    @egreso_internos = buscar(params[:palabra])
  end

  def buscar(interno)
    items = Array.new
    aux = EgresoInterno.all
    if interno != "" && interno != nil
      aux.each do |item|
        if(item.correspondeAinterno(interno))
          items.push(item)
        end
      end
    else
      items = aux
    end
    return items
  end

  # GET /egreso_internos/1
  # GET /egreso_internos/1.json
  def show
  end

  def dinero_actual()
    @total=0
    @total_egreso=0
    @total_egreso_interno=0

    @ingresos= Ingreso.all
    @egresos=Egreso.all
    @egreso_internos=EgresoInterno.all

    @ingresos.each do |ingreso| 
      if (ingreso.montoBs != nil)
        @total += ingreso.montoBs
      end
    end

    @egresos.each do |egreso| 
      if (egreso.monto != nil)
        @total_egreso += egreso.monto
      end
    end
    
    @egreso_internos.each do |egreso_interno| 
      if (egreso_interno.monto != nil)
        @total_egreso_interno += egreso_interno.monto
      end
    end

    @total=@total-@total_egreso-@total_egreso_interno
    return @total
  end

  # GET /egreso_internos/new
  def new
    @egreso_interno = EgresoInterno.new
    # @interno = Interno.find_by_id(:interno_id)
    # @egreso_interno.interno = @interno
    @id=(params[:id])
    @total=dinero_actual
  end

  # GET /egreso_internos/1/edit
  def edit
  end

  # POST /egreso_internos
  # POST /egreso_internos.json
  def create
    @egreso_interno = EgresoInterno.new(egreso_interno_params)
    @egreso_interno.interno_id=params[:interno_id]
    @id = @egreso_interno.interno_id
    @total=dinero_actual
    
    if @egreso_interno.monto>@total
      flash[:warning] = 'El monto de egreso no puede ser mayor al monto total'
      render action: "new"
    else   
      if @egreso_interno.save
        flash[:success] = 'Egreso Interno creado exitosamente'
        redirect_to @egreso_interno
      else
        render action: "new"
      end
    end
  end

  # PATCH/PUT /egreso_internos/1
  # PATCH/PUT /egreso_internos/1.json
  def update
    @egreso_interno = EgresoInterno.find(params[:id])
    @total=dinero_actual
    if @egreso_interno.monto>@total
      flash[:warning] = 'El monto de egreso no puede ser mayor al monto actual'
      render action: "edit"
    else
      if @egreso_interno.update(egreso_interno_params)
        flash[:success] = "Egreso Interno actualizado exitosamente"
        redirect_to @egreso_interno
      else
        render action: "edit"
      end
    end
  end

  # DELETE /egreso_internos/1
  # DELETE /egreso_internos/1.json
  def destroy
    @egreso_interno.destroy
    respond_to do |format|
      format.html { redirect_to egreso_internos_url, notice: 'Egreso interno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_egreso_interno
      @egreso_interno = EgresoInterno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def egreso_interno_params
      params.require(:egreso_interno).permit(:concepto, :monto, :observaciones, :fecha, :interno_id, :egreso_id)
    end
end

app/helpers/egreso_internos_helper.rb
module EgresoInternosHelper
end

app/views/egreso_internos/_form.html.erb
<%= form_for(@egreso_interno) do |f| %>
  <% if @egreso_interno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@egreso_interno.errors.count, "error") %>, corrija los siguientes errores:</h2>

      <ul>
      <% @egreso_interno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <input type="hidden" name="interno_id" value="<%= @id %>" >
  <br>
  <table>
    <tr>
      <td>
        <div class="field">
          <%= f.label :concepto, 'Concepto *' %><br>
          <%= f.text_field :concepto %>
        </div>
      </td>
      <td width="100px"></td>
      <td>
        <div class="field">
          <%= f.label :monto, 'Monto Bs. *' %><br>
          <%= f.text_field :monto %>
        </div>
      </td>
    </tr>
    <tr height="15px"></tr>
    <tr>
      <td>
        <div class="field">
          <%= f.label :observaciones %><br>
          <%= f.text_area :observaciones %>
        </div>
      </td>
      <td width="100px"></td>
      <td>
        <div class="field">
          <%= f.label :fecha, 'Fecha *' %><br>
          <%= f.date_select :fecha %>
        </div>
      </td>
    </tr>
  </table>
  <br><br>
  <div>
    <label>* Los campos con asterisco, son obligatorios. </label>
  </div><br><br>
  <div class="actions" align="center">
    <%= f.submit (@egreso_interno.new_record? ? 'Registrar Egreso Interno' : 'Editar Egreso Interno') , :class => "btn btn-sm btn-success" %> |
    <%= link_to 'Retornar a Internos', :back, :class => 'btn btn-sm btn-default' %>
  </div>
<% end %>

app/views/egreso_internos/edit.html.erb
<center>
	<div id="cuadro">
		<div id="titulo">Editar Egreso Interno</div>
		<div id="linea"></div>
		<%= render 'form' %>
	</div>
</center>

app/views/egreso_internos/index.html.erb
<h1>Lista de Egreso Interno</h1>

  <div align="right">
    <%= form_tag({:controller => "egreso_internos", :action => "index"}, :method => :get) do %>
      Buscar Interno: &nbsp;&nbsp;&nbsp; <%= text_field_tag "searchbox", params[:searchbox], :placeholder => "Nombre de Interno", :name => 'palabra' %> &nbsp;&nbsp;&nbsp;
      <%= submit_tag "Buscar", :name => nil, :class => 'btn btn-mini' %>
    <% end %>
  </div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Interno</th>
      <th>Concepto</th>
      <th>Monto Bs.</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @egreso_internos.each do |egreso_interno| %>
      <tr>
        <td><%= Interno.find(egreso_interno.interno_id.to_i).nombre %></td>
        <td><%= egreso_interno.concepto %></td>
        <td><%= egreso_interno.monto %></td>
        <td><%= link_to 'Ver Egreso Interno', egreso_interno, :class => 'btn btn-mini btn-info active' %></td>
        <td><%= link_to 'Editar Egreso Interno', edit_egreso_interno_path(egreso_interno), :class => 'btn btn-mini btn-warning active' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><br>

<%= link_to 'Registrar Egreso Interno', new_egreso_interno_path, :class => 'btn btn-mini btn-success active' %>

app/views/egreso_internos/new.html.erb
<center>
	<div id="cuadro">
		<div id="titulo">Registrar Egreso Interno</div>
		<div id="linea"></div>
		<div id="subtitulo">Dinero Actual en Bs: <%=@total%></div><br>
		<%= render 'form' %>
	</div>
</center>

app/views/egreso_internos/show.html.erb
<center>
  <p id="notice"><%= notice %></p>

  <h1>Egresos de <%= @egreso_interno.interno.nombre %> </h1><br>
  <div align="right"><%= link_to 'Internos', internos_path, :class => 'btn btn-mini btn-default' %> | 
    <%= link_to 'Atras', :back, :class => 'btn btn-mini btn-default' %></div>

  <p>
    <strong>Concepto:</strong>
    <%= @egreso_interno.concepto %>
  </p>

  <p>
    <strong>Monto Bs.:</strong>
    <%= @egreso_interno.monto %>
  </p>

  <p>
    <strong>Observaciones:</strong>
    <%= @egreso_interno.observaciones %>
  </p>

  <p>
    <strong>Fecha:</strong>
    <%= @egreso_interno.fecha.strftime("%d/%m/%Y") %>
  </p>
</center>